mutation CreateAssembly(
  $name: String!
  $isRequired: Boolean!
  $isActive: Boolean!
  $configs: [AssemblyOptionConfigInput]!
) {
  createAssemblyOption(
    assemblyOption: {
      name: $name
      isRequired: $isRequired
      isActive: $isActive
      configs: [
        {
          name: "key 1"
          minItems: 0
          maxItems: 3
          items: [
            {
              skuId: "123"
              minValue: 0
              maxValue: 2
              defaultValue: 1
              priceTable: "testeTable"
            }
          ]
        }
      ]
    }
  ) {
    id
    name
    isRequired
    isActive
    configs {
      name
      minItems
      maxItems
      items {
        skuId
        minValue
        maxValue
        defaultValue
        priceTable
      }
    }
  }
}
