query GetAssemblyOption($id: ID!) {
  getAssemblyOption(id: $id) {
    id
    name
    isRequired
    isActive
    configs {
      name
      minItems
      maxItems
      items {
        skuId
        defaultValue
        priceTable
        minValue
        maxValue
      }
    }
  }
}
