query ListAssemblyOptions(
  $page: Int
  $perPage: Int
  $name: String
  $active: Boolean
) {
  listAssemblyOptions(
    page: $page
    perPage: $perPage
    name: $name
    active: $active
  ) {
    data {
      id
      assemblyOptionId: id
      name
      isRequired
      isActive
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
